language: php
php:
  - 7.3

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

install:
  - composer update $DEFAULT_COMPOSER_FLAGS

script:
  - phpunit --bootstrap vendor/autoload.php --whitelist=src/ --coverage-clover=coverage.xml tests/

after_success:
  - bash <(curl -s --connect-timeout 300 --max-time 330 https://codecov.io/bash)

notifications:
  email: true
